Add friends likes
swwwer82/java-filmorate pull request #6
Opened 2024-02-27 19:09 UTC by swwwer82

2024-02-27 20:32 UTC, andrew-larkin requested changes
Привет! Очень хорошо реализовал новый функционал, все чисто и по делу, молодец! Пара правок в интерфейсах Storage и нужно дописать тесты на новый функционал - и работа будет принята.

2024-02-27 20:32 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public long getNextId() {
getNextId актуален для конкретной реализации интерфейса, поэтому оттуда этот метод удаляем

2024-02-27 20:32 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    public long getNextId() {
такая же ситуация

2024-03-02 10:42 UTC, swwwer82 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public long getNextId() {
Сделано

2024-03-02 10:42 UTC, swwwer82 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    public long getNextId() {
Сделано

2024-03-02 17:07 UTC, merged