done
swwwer82/java-filmorate pull request #9
Opened 2024-03-14 11:57 UTC by swwwer82

2024-03-15 22:14 UTC, andrew-larkin requested changes
Привет! Новый функционал реализован просто отлично, даже придраться не к чему. В паре мест поправить и работа будет принята.

2024-03-15 22:14 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>  @Data
@Data лучше не использовать в моделях - она может некорректно рассчитывать хэш. Вместо нее можно использовать @Getter, @Setter и т.д.

2024-03-15 22:14 UTC, andrew-larkin commented on src/main/resources/schema.sql
> +-- Drop table
закомментированные строки удаляем

2024-03-16 11:36 UTC, swwwer82 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>  @Data
сделано

2024-03-16 11:36 UTC, swwwer82 commented on src/main/resources/schema.sql
> +-- Drop table
сделано

2024-03-17 07:56 UTC, merged